package com.lim.cms.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sim_calendar
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SimCalendar extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_calendar.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_calendar.start
     *
     * @mbg.generated
     */
    private Date start;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_calendar.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_calendar.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_calendar.end
     *
     * @mbg.generated
     */
    private Date end;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_calendar.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_calendar.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_calendar.id
     *
     * @return the value of sim_calendar.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_calendar.id
     *
     * @param id the value for sim_calendar.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_calendar.start
     *
     * @return the value of sim_calendar.start
     *
     * @mbg.generated
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_calendar.start
     *
     * @param start the value for sim_calendar.start
     *
     * @mbg.generated
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_calendar.title
     *
     * @return the value of sim_calendar.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_calendar.title
     *
     * @param title the value for sim_calendar.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_calendar.user_id
     *
     * @return the value of sim_calendar.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_calendar.user_id
     *
     * @param userId the value for sim_calendar.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_calendar.end
     *
     * @return the value of sim_calendar.end
     *
     * @mbg.generated
     */
    public Date getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_calendar.end
     *
     * @param end the value for sim_calendar.end
     *
     * @mbg.generated
     */
    public void setEnd(Date end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_calendar.description
     *
     * @return the value of sim_calendar.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_calendar.description
     *
     * @param description the value for sim_calendar.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_calendar.color
     *
     * @return the value of sim_calendar.color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_calendar.color
     *
     * @param color the value for sim_calendar.color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color;
    }
}