package com.lim.cms.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sim_company
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SimCompany extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.company
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.cf1
     *
     * @mbg.generated
     */
    private String cf1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.cf2
     *
     * @mbg.generated
     */
    private String cf2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.cf3
     *
     * @mbg.generated
     */
    private String cf3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.cf4
     *
     * @mbg.generated
     */
    private String cf4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.cf5
     *
     * @mbg.generated
     */
    private String cf5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.cf6
     *
     * @mbg.generated
     */
    private String cf6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.postal_code
     *
     * @mbg.generated
     */
    private String postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.ss_image
     *
     * @mbg.generated
     */
    private String ssImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_company.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.id
     *
     * @return the value of sim_company.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.id
     *
     * @param id the value for sim_company.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.name
     *
     * @return the value of sim_company.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.name
     *
     * @param name the value for sim_company.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.company
     *
     * @return the value of sim_company.company
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.company
     *
     * @param company the value for sim_company.company
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.cf1
     *
     * @return the value of sim_company.cf1
     *
     * @mbg.generated
     */
    public String getCf1() {
        return cf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.cf1
     *
     * @param cf1 the value for sim_company.cf1
     *
     * @mbg.generated
     */
    public void setCf1(String cf1) {
        this.cf1 = cf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.cf2
     *
     * @return the value of sim_company.cf2
     *
     * @mbg.generated
     */
    public String getCf2() {
        return cf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.cf2
     *
     * @param cf2 the value for sim_company.cf2
     *
     * @mbg.generated
     */
    public void setCf2(String cf2) {
        this.cf2 = cf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.cf3
     *
     * @return the value of sim_company.cf3
     *
     * @mbg.generated
     */
    public String getCf3() {
        return cf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.cf3
     *
     * @param cf3 the value for sim_company.cf3
     *
     * @mbg.generated
     */
    public void setCf3(String cf3) {
        this.cf3 = cf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.cf4
     *
     * @return the value of sim_company.cf4
     *
     * @mbg.generated
     */
    public String getCf4() {
        return cf4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.cf4
     *
     * @param cf4 the value for sim_company.cf4
     *
     * @mbg.generated
     */
    public void setCf4(String cf4) {
        this.cf4 = cf4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.cf5
     *
     * @return the value of sim_company.cf5
     *
     * @mbg.generated
     */
    public String getCf5() {
        return cf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.cf5
     *
     * @param cf5 the value for sim_company.cf5
     *
     * @mbg.generated
     */
    public void setCf5(String cf5) {
        this.cf5 = cf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.cf6
     *
     * @return the value of sim_company.cf6
     *
     * @mbg.generated
     */
    public String getCf6() {
        return cf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.cf6
     *
     * @param cf6 the value for sim_company.cf6
     *
     * @mbg.generated
     */
    public void setCf6(String cf6) {
        this.cf6 = cf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.address
     *
     * @return the value of sim_company.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.address
     *
     * @param address the value for sim_company.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.city
     *
     * @return the value of sim_company.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.city
     *
     * @param city the value for sim_company.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.state
     *
     * @return the value of sim_company.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.state
     *
     * @param state the value for sim_company.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.postal_code
     *
     * @return the value of sim_company.postal_code
     *
     * @mbg.generated
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.postal_code
     *
     * @param postalCode the value for sim_company.postal_code
     *
     * @mbg.generated
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.country
     *
     * @return the value of sim_company.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.country
     *
     * @param country the value for sim_company.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.phone
     *
     * @return the value of sim_company.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.phone
     *
     * @param phone the value for sim_company.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.email
     *
     * @return the value of sim_company.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.email
     *
     * @param email the value for sim_company.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.logo
     *
     * @return the value of sim_company.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.logo
     *
     * @param logo the value for sim_company.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.ss_image
     *
     * @return the value of sim_company.ss_image
     *
     * @mbg.generated
     */
    public String getSsImage() {
        return ssImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.ss_image
     *
     * @param ssImage the value for sim_company.ss_image
     *
     * @mbg.generated
     */
    public void setSsImage(String ssImage) {
        this.ssImage = ssImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_company.status
     *
     * @return the value of sim_company.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_company.status
     *
     * @param status the value for sim_company.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}