package com.lim.cms.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sim_date_format
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SimDateFormat extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_date_format.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_date_format.js
     *
     * @mbg.generated
     */
    private String js;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_date_format.php
     *
     * @mbg.generated
     */
    private String php;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_date_format.sql
     *
     * @mbg.generated
     */
    private String sql;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_date_format.id
     *
     * @return the value of sim_date_format.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_date_format.id
     *
     * @param id the value for sim_date_format.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_date_format.js
     *
     * @return the value of sim_date_format.js
     *
     * @mbg.generated
     */
    public String getJs() {
        return js;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_date_format.js
     *
     * @param js the value for sim_date_format.js
     *
     * @mbg.generated
     */
    public void setJs(String js) {
        this.js = js;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_date_format.php
     *
     * @return the value of sim_date_format.php
     *
     * @mbg.generated
     */
    public String getPhp() {
        return php;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_date_format.php
     *
     * @param php the value for sim_date_format.php
     *
     * @mbg.generated
     */
    public void setPhp(String php) {
        this.php = php;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_date_format.sql
     *
     * @return the value of sim_date_format.sql
     *
     * @mbg.generated
     */
    public String getSql() {
        return sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_date_format.sql
     *
     * @param sql the value for sim_date_format.sql
     *
     * @mbg.generated
     */
    public void setSql(String sql) {
        this.sql = sql;
    }
}