package com.lim.cms.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sim_login_attempts
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SimLoginAttempts extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_login_attempts.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_login_attempts.login
     *
     * @mbg.generated
     */
    private String login;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_login_attempts.time
     *
     * @mbg.generated
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_login_attempts.ip_address
     *
     * @mbg.generated
     */
    private byte[] ipAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_login_attempts.id
     *
     * @return the value of sim_login_attempts.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_login_attempts.id
     *
     * @param id the value for sim_login_attempts.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_login_attempts.login
     *
     * @return the value of sim_login_attempts.login
     *
     * @mbg.generated
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_login_attempts.login
     *
     * @param login the value for sim_login_attempts.login
     *
     * @mbg.generated
     */
    public void setLogin(String login) {
        this.login = login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_login_attempts.time
     *
     * @return the value of sim_login_attempts.time
     *
     * @mbg.generated
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_login_attempts.time
     *
     * @param time the value for sim_login_attempts.time
     *
     * @mbg.generated
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_login_attempts.ip_address
     *
     * @return the value of sim_login_attempts.ip_address
     *
     * @mbg.generated
     */
    public byte[] getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_login_attempts.ip_address
     *
     * @param ipAddress the value for sim_login_attempts.ip_address
     *
     * @mbg.generated
     */
    public void setIpAddress(byte[] ipAddress) {
        this.ipAddress = ipAddress;
    }
}