package com.lim.cms.entity;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sim_paypal
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SimPaypal extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_paypal.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_paypal.active
     *
     * @mbg.generated
     */
    private Byte active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_paypal.account_email
     *
     * @mbg.generated
     */
    private String accountEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_paypal.fixed_charges
     *
     * @mbg.generated
     */
    private BigDecimal fixedCharges;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_paypal.extra_charges_my
     *
     * @mbg.generated
     */
    private BigDecimal extraChargesMy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_paypal.extra_charges_other
     *
     * @mbg.generated
     */
    private BigDecimal extraChargesOther;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_paypal.id
     *
     * @return the value of sim_paypal.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_paypal.id
     *
     * @param id the value for sim_paypal.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_paypal.active
     *
     * @return the value of sim_paypal.active
     *
     * @mbg.generated
     */
    public Byte getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_paypal.active
     *
     * @param active the value for sim_paypal.active
     *
     * @mbg.generated
     */
    public void setActive(Byte active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_paypal.account_email
     *
     * @return the value of sim_paypal.account_email
     *
     * @mbg.generated
     */
    public String getAccountEmail() {
        return accountEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_paypal.account_email
     *
     * @param accountEmail the value for sim_paypal.account_email
     *
     * @mbg.generated
     */
    public void setAccountEmail(String accountEmail) {
        this.accountEmail = accountEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_paypal.fixed_charges
     *
     * @return the value of sim_paypal.fixed_charges
     *
     * @mbg.generated
     */
    public BigDecimal getFixedCharges() {
        return fixedCharges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_paypal.fixed_charges
     *
     * @param fixedCharges the value for sim_paypal.fixed_charges
     *
     * @mbg.generated
     */
    public void setFixedCharges(BigDecimal fixedCharges) {
        this.fixedCharges = fixedCharges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_paypal.extra_charges_my
     *
     * @return the value of sim_paypal.extra_charges_my
     *
     * @mbg.generated
     */
    public BigDecimal getExtraChargesMy() {
        return extraChargesMy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_paypal.extra_charges_my
     *
     * @param extraChargesMy the value for sim_paypal.extra_charges_my
     *
     * @mbg.generated
     */
    public void setExtraChargesMy(BigDecimal extraChargesMy) {
        this.extraChargesMy = extraChargesMy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_paypal.extra_charges_other
     *
     * @return the value of sim_paypal.extra_charges_other
     *
     * @mbg.generated
     */
    public BigDecimal getExtraChargesOther() {
        return extraChargesOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_paypal.extra_charges_other
     *
     * @param extraChargesOther the value for sim_paypal.extra_charges_other
     *
     * @mbg.generated
     */
    public void setExtraChargesOther(BigDecimal extraChargesOther) {
        this.extraChargesOther = extraChargesOther;
    }
}