package com.lim.cms.entity;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sim_products
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SimProducts extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_products.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_products.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_products.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_products.tax_rate
     *
     * @mbg.generated
     */
    private Integer taxRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_products.details
     *
     * @mbg.generated
     */
    private String details;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_products.tax_method
     *
     * @mbg.generated
     */
    private String taxMethod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_products.id
     *
     * @return the value of sim_products.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_products.id
     *
     * @param id the value for sim_products.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_products.name
     *
     * @return the value of sim_products.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_products.name
     *
     * @param name the value for sim_products.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_products.price
     *
     * @return the value of sim_products.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_products.price
     *
     * @param price the value for sim_products.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_products.tax_rate
     *
     * @return the value of sim_products.tax_rate
     *
     * @mbg.generated
     */
    public Integer getTaxRate() {
        return taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_products.tax_rate
     *
     * @param taxRate the value for sim_products.tax_rate
     *
     * @mbg.generated
     */
    public void setTaxRate(Integer taxRate) {
        this.taxRate = taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_products.details
     *
     * @return the value of sim_products.details
     *
     * @mbg.generated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_products.details
     *
     * @param details the value for sim_products.details
     *
     * @mbg.generated
     */
    public void setDetails(String details) {
        this.details = details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_products.tax_method
     *
     * @return the value of sim_products.tax_method
     *
     * @mbg.generated
     */
    public String getTaxMethod() {
        return taxMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_products.tax_method
     *
     * @param taxMethod the value for sim_products.tax_method
     *
     * @mbg.generated
     */
    public void setTaxMethod(String taxMethod) {
        this.taxMethod = taxMethod;
    }
}