package com.lim.cms.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sim_quotes
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SimQuotes extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.reference_no
     *
     * @mbg.generated
     */
    private String referenceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.customer_name
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.user
     *
     * @mbg.generated
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.total
     *
     * @mbg.generated
     */
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.total_tax
     *
     * @mbg.generated
     */
    private BigDecimal totalTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.grand_total
     *
     * @mbg.generated
     */
    private BigDecimal grandTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.shipping
     *
     * @mbg.generated
     */
    private BigDecimal shipping;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.order_discount_id
     *
     * @mbg.generated
     */
    private String orderDiscountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.total_discount
     *
     * @mbg.generated
     */
    private BigDecimal totalDiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.expiry_date
     *
     * @mbg.generated
     */
    private Date expiryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.product_discount
     *
     * @mbg.generated
     */
    private BigDecimal productDiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.order_discount
     *
     * @mbg.generated
     */
    private BigDecimal orderDiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.product_tax
     *
     * @mbg.generated
     */
    private BigDecimal productTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.order_tax_id
     *
     * @mbg.generated
     */
    private Integer orderTaxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.order_tax
     *
     * @mbg.generated
     */
    private BigDecimal orderTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quotes.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.id
     *
     * @return the value of sim_quotes.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.id
     *
     * @param id the value for sim_quotes.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.reference_no
     *
     * @return the value of sim_quotes.reference_no
     *
     * @mbg.generated
     */
    public String getReferenceNo() {
        return referenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.reference_no
     *
     * @param referenceNo the value for sim_quotes.reference_no
     *
     * @mbg.generated
     */
    public void setReferenceNo(String referenceNo) {
        this.referenceNo = referenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.customer_id
     *
     * @return the value of sim_quotes.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.customer_id
     *
     * @param customerId the value for sim_quotes.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.customer_name
     *
     * @return the value of sim_quotes.customer_name
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.customer_name
     *
     * @param customerName the value for sim_quotes.customer_name
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.date
     *
     * @return the value of sim_quotes.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.date
     *
     * @param date the value for sim_quotes.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.user
     *
     * @return the value of sim_quotes.user
     *
     * @mbg.generated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.user
     *
     * @param user the value for sim_quotes.user
     *
     * @mbg.generated
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.note
     *
     * @return the value of sim_quotes.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.note
     *
     * @param note the value for sim_quotes.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.total
     *
     * @return the value of sim_quotes.total
     *
     * @mbg.generated
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.total
     *
     * @param total the value for sim_quotes.total
     *
     * @mbg.generated
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.total_tax
     *
     * @return the value of sim_quotes.total_tax
     *
     * @mbg.generated
     */
    public BigDecimal getTotalTax() {
        return totalTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.total_tax
     *
     * @param totalTax the value for sim_quotes.total_tax
     *
     * @mbg.generated
     */
    public void setTotalTax(BigDecimal totalTax) {
        this.totalTax = totalTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.grand_total
     *
     * @return the value of sim_quotes.grand_total
     *
     * @mbg.generated
     */
    public BigDecimal getGrandTotal() {
        return grandTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.grand_total
     *
     * @param grandTotal the value for sim_quotes.grand_total
     *
     * @mbg.generated
     */
    public void setGrandTotal(BigDecimal grandTotal) {
        this.grandTotal = grandTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.user_id
     *
     * @return the value of sim_quotes.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.user_id
     *
     * @param userId the value for sim_quotes.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.shipping
     *
     * @return the value of sim_quotes.shipping
     *
     * @mbg.generated
     */
    public BigDecimal getShipping() {
        return shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.shipping
     *
     * @param shipping the value for sim_quotes.shipping
     *
     * @mbg.generated
     */
    public void setShipping(BigDecimal shipping) {
        this.shipping = shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.order_discount_id
     *
     * @return the value of sim_quotes.order_discount_id
     *
     * @mbg.generated
     */
    public String getOrderDiscountId() {
        return orderDiscountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.order_discount_id
     *
     * @param orderDiscountId the value for sim_quotes.order_discount_id
     *
     * @mbg.generated
     */
    public void setOrderDiscountId(String orderDiscountId) {
        this.orderDiscountId = orderDiscountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.total_discount
     *
     * @return the value of sim_quotes.total_discount
     *
     * @mbg.generated
     */
    public BigDecimal getTotalDiscount() {
        return totalDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.total_discount
     *
     * @param totalDiscount the value for sim_quotes.total_discount
     *
     * @mbg.generated
     */
    public void setTotalDiscount(BigDecimal totalDiscount) {
        this.totalDiscount = totalDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.company_id
     *
     * @return the value of sim_quotes.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.company_id
     *
     * @param companyId the value for sim_quotes.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.expiry_date
     *
     * @return the value of sim_quotes.expiry_date
     *
     * @mbg.generated
     */
    public Date getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.expiry_date
     *
     * @param expiryDate the value for sim_quotes.expiry_date
     *
     * @mbg.generated
     */
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.status
     *
     * @return the value of sim_quotes.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.status
     *
     * @param status the value for sim_quotes.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.product_discount
     *
     * @return the value of sim_quotes.product_discount
     *
     * @mbg.generated
     */
    public BigDecimal getProductDiscount() {
        return productDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.product_discount
     *
     * @param productDiscount the value for sim_quotes.product_discount
     *
     * @mbg.generated
     */
    public void setProductDiscount(BigDecimal productDiscount) {
        this.productDiscount = productDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.order_discount
     *
     * @return the value of sim_quotes.order_discount
     *
     * @mbg.generated
     */
    public BigDecimal getOrderDiscount() {
        return orderDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.order_discount
     *
     * @param orderDiscount the value for sim_quotes.order_discount
     *
     * @mbg.generated
     */
    public void setOrderDiscount(BigDecimal orderDiscount) {
        this.orderDiscount = orderDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.product_tax
     *
     * @return the value of sim_quotes.product_tax
     *
     * @mbg.generated
     */
    public BigDecimal getProductTax() {
        return productTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.product_tax
     *
     * @param productTax the value for sim_quotes.product_tax
     *
     * @mbg.generated
     */
    public void setProductTax(BigDecimal productTax) {
        this.productTax = productTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.order_tax_id
     *
     * @return the value of sim_quotes.order_tax_id
     *
     * @mbg.generated
     */
    public Integer getOrderTaxId() {
        return orderTaxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.order_tax_id
     *
     * @param orderTaxId the value for sim_quotes.order_tax_id
     *
     * @mbg.generated
     */
    public void setOrderTaxId(Integer orderTaxId) {
        this.orderTaxId = orderTaxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.order_tax
     *
     * @return the value of sim_quotes.order_tax
     *
     * @mbg.generated
     */
    public BigDecimal getOrderTax() {
        return orderTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.order_tax
     *
     * @param orderTax the value for sim_quotes.order_tax
     *
     * @mbg.generated
     */
    public void setOrderTax(BigDecimal orderTax) {
        this.orderTax = orderTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quotes.company_name
     *
     * @return the value of sim_quotes.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quotes.company_name
     *
     * @param companyName the value for sim_quotes.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
}