package com.lim.cms.entity;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sim_quote_items
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SimQuoteItems extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quote_items.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quote_items.quote_id
     *
     * @mbg.generated
     */
    private Integer quoteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quote_items.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quote_items.tax_rate_id
     *
     * @mbg.generated
     */
    private Integer taxRateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quote_items.tax
     *
     * @mbg.generated
     */
    private String tax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quote_items.quantity
     *
     * @mbg.generated
     */
    private BigDecimal quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quote_items.unit_price
     *
     * @mbg.generated
     */
    private BigDecimal unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quote_items.subtotal
     *
     * @mbg.generated
     */
    private BigDecimal subtotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quote_items.tax_amt
     *
     * @mbg.generated
     */
    private BigDecimal taxAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quote_items.details
     *
     * @mbg.generated
     */
    private String details;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quote_items.net_unit_price
     *
     * @mbg.generated
     */
    private BigDecimal netUnitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quote_items.real_unit_price
     *
     * @mbg.generated
     */
    private BigDecimal realUnitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quote_items.discount
     *
     * @mbg.generated
     */
    private String discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quote_items.discount_amt
     *
     * @mbg.generated
     */
    private BigDecimal discountAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_quote_items.tax_method
     *
     * @mbg.generated
     */
    private String taxMethod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quote_items.id
     *
     * @return the value of sim_quote_items.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quote_items.id
     *
     * @param id the value for sim_quote_items.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quote_items.quote_id
     *
     * @return the value of sim_quote_items.quote_id
     *
     * @mbg.generated
     */
    public Integer getQuoteId() {
        return quoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quote_items.quote_id
     *
     * @param quoteId the value for sim_quote_items.quote_id
     *
     * @mbg.generated
     */
    public void setQuoteId(Integer quoteId) {
        this.quoteId = quoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quote_items.product_name
     *
     * @return the value of sim_quote_items.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quote_items.product_name
     *
     * @param productName the value for sim_quote_items.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quote_items.tax_rate_id
     *
     * @return the value of sim_quote_items.tax_rate_id
     *
     * @mbg.generated
     */
    public Integer getTaxRateId() {
        return taxRateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quote_items.tax_rate_id
     *
     * @param taxRateId the value for sim_quote_items.tax_rate_id
     *
     * @mbg.generated
     */
    public void setTaxRateId(Integer taxRateId) {
        this.taxRateId = taxRateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quote_items.tax
     *
     * @return the value of sim_quote_items.tax
     *
     * @mbg.generated
     */
    public String getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quote_items.tax
     *
     * @param tax the value for sim_quote_items.tax
     *
     * @mbg.generated
     */
    public void setTax(String tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quote_items.quantity
     *
     * @return the value of sim_quote_items.quantity
     *
     * @mbg.generated
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quote_items.quantity
     *
     * @param quantity the value for sim_quote_items.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quote_items.unit_price
     *
     * @return the value of sim_quote_items.unit_price
     *
     * @mbg.generated
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quote_items.unit_price
     *
     * @param unitPrice the value for sim_quote_items.unit_price
     *
     * @mbg.generated
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quote_items.subtotal
     *
     * @return the value of sim_quote_items.subtotal
     *
     * @mbg.generated
     */
    public BigDecimal getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quote_items.subtotal
     *
     * @param subtotal the value for sim_quote_items.subtotal
     *
     * @mbg.generated
     */
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quote_items.tax_amt
     *
     * @return the value of sim_quote_items.tax_amt
     *
     * @mbg.generated
     */
    public BigDecimal getTaxAmt() {
        return taxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quote_items.tax_amt
     *
     * @param taxAmt the value for sim_quote_items.tax_amt
     *
     * @mbg.generated
     */
    public void setTaxAmt(BigDecimal taxAmt) {
        this.taxAmt = taxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quote_items.details
     *
     * @return the value of sim_quote_items.details
     *
     * @mbg.generated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quote_items.details
     *
     * @param details the value for sim_quote_items.details
     *
     * @mbg.generated
     */
    public void setDetails(String details) {
        this.details = details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quote_items.net_unit_price
     *
     * @return the value of sim_quote_items.net_unit_price
     *
     * @mbg.generated
     */
    public BigDecimal getNetUnitPrice() {
        return netUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quote_items.net_unit_price
     *
     * @param netUnitPrice the value for sim_quote_items.net_unit_price
     *
     * @mbg.generated
     */
    public void setNetUnitPrice(BigDecimal netUnitPrice) {
        this.netUnitPrice = netUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quote_items.real_unit_price
     *
     * @return the value of sim_quote_items.real_unit_price
     *
     * @mbg.generated
     */
    public BigDecimal getRealUnitPrice() {
        return realUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quote_items.real_unit_price
     *
     * @param realUnitPrice the value for sim_quote_items.real_unit_price
     *
     * @mbg.generated
     */
    public void setRealUnitPrice(BigDecimal realUnitPrice) {
        this.realUnitPrice = realUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quote_items.discount
     *
     * @return the value of sim_quote_items.discount
     *
     * @mbg.generated
     */
    public String getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quote_items.discount
     *
     * @param discount the value for sim_quote_items.discount
     *
     * @mbg.generated
     */
    public void setDiscount(String discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quote_items.discount_amt
     *
     * @return the value of sim_quote_items.discount_amt
     *
     * @mbg.generated
     */
    public BigDecimal getDiscountAmt() {
        return discountAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quote_items.discount_amt
     *
     * @param discountAmt the value for sim_quote_items.discount_amt
     *
     * @mbg.generated
     */
    public void setDiscountAmt(BigDecimal discountAmt) {
        this.discountAmt = discountAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_quote_items.tax_method
     *
     * @return the value of sim_quote_items.tax_method
     *
     * @mbg.generated
     */
    public String getTaxMethod() {
        return taxMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_quote_items.tax_method
     *
     * @param taxMethod the value for sim_quote_items.tax_method
     *
     * @mbg.generated
     */
    public void setTaxMethod(String taxMethod) {
        this.taxMethod = taxMethod;
    }
}