package com.lim.cms.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sim_settings
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SimSettings extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.setting_id
     *
     * @mbg.generated
     */
    private Integer settingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.invoice_logo
     *
     * @mbg.generated
     */
    private String invoiceLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.site_name
     *
     * @mbg.generated
     */
    private String siteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.language
     *
     * @mbg.generated
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.currency_prefix
     *
     * @mbg.generated
     */
    private String currencyPrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.default_tax_rate
     *
     * @mbg.generated
     */
    private Integer defaultTaxRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.rows_per_page
     *
     * @mbg.generated
     */
    private Integer rowsPerPage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.no_of_rows
     *
     * @mbg.generated
     */
    private Integer noOfRows;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.total_rows
     *
     * @mbg.generated
     */
    private Integer totalRows;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.dateformat
     *
     * @mbg.generated
     */
    private Byte dateformat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.print_payment
     *
     * @mbg.generated
     */
    private Byte printPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.calendar
     *
     * @mbg.generated
     */
    private Byte calendar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.restrict_sales
     *
     * @mbg.generated
     */
    private Byte restrictSales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.major
     *
     * @mbg.generated
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.minor
     *
     * @mbg.generated
     */
    private String minor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.display_words
     *
     * @mbg.generated
     */
    private Byte displayWords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.customer_user
     *
     * @mbg.generated
     */
    private Boolean customerUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.email_html
     *
     * @mbg.generated
     */
    private Boolean emailHtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.protocol
     *
     * @mbg.generated
     */
    private String protocol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.mailpath
     *
     * @mbg.generated
     */
    private String mailpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.smtp_host
     *
     * @mbg.generated
     */
    private String smtpHost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.smtp_user
     *
     * @mbg.generated
     */
    private String smtpUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.smtp_pass
     *
     * @mbg.generated
     */
    private String smtpPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.smtp_port
     *
     * @mbg.generated
     */
    private String smtpPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.smtp_crypto
     *
     * @mbg.generated
     */
    private String smtpCrypto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.thousands_sep
     *
     * @mbg.generated
     */
    private String thousandsSep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.decimals_sep
     *
     * @mbg.generated
     */
    private String decimalsSep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.decimals
     *
     * @mbg.generated
     */
    private Byte decimals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.default_email
     *
     * @mbg.generated
     */
    private String defaultEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.purchase_code
     *
     * @mbg.generated
     */
    private String purchaseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.envato_username
     *
     * @mbg.generated
     */
    private String envatoUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.theme
     *
     * @mbg.generated
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_settings.product_discount
     *
     * @mbg.generated
     */
    private Boolean productDiscount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.setting_id
     *
     * @return the value of sim_settings.setting_id
     *
     * @mbg.generated
     */
    public Integer getSettingId() {
        return settingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.setting_id
     *
     * @param settingId the value for sim_settings.setting_id
     *
     * @mbg.generated
     */
    public void setSettingId(Integer settingId) {
        this.settingId = settingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.logo
     *
     * @return the value of sim_settings.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.logo
     *
     * @param logo the value for sim_settings.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.invoice_logo
     *
     * @return the value of sim_settings.invoice_logo
     *
     * @mbg.generated
     */
    public String getInvoiceLogo() {
        return invoiceLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.invoice_logo
     *
     * @param invoiceLogo the value for sim_settings.invoice_logo
     *
     * @mbg.generated
     */
    public void setInvoiceLogo(String invoiceLogo) {
        this.invoiceLogo = invoiceLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.site_name
     *
     * @return the value of sim_settings.site_name
     *
     * @mbg.generated
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.site_name
     *
     * @param siteName the value for sim_settings.site_name
     *
     * @mbg.generated
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.language
     *
     * @return the value of sim_settings.language
     *
     * @mbg.generated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.language
     *
     * @param language the value for sim_settings.language
     *
     * @mbg.generated
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.currency_prefix
     *
     * @return the value of sim_settings.currency_prefix
     *
     * @mbg.generated
     */
    public String getCurrencyPrefix() {
        return currencyPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.currency_prefix
     *
     * @param currencyPrefix the value for sim_settings.currency_prefix
     *
     * @mbg.generated
     */
    public void setCurrencyPrefix(String currencyPrefix) {
        this.currencyPrefix = currencyPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.default_tax_rate
     *
     * @return the value of sim_settings.default_tax_rate
     *
     * @mbg.generated
     */
    public Integer getDefaultTaxRate() {
        return defaultTaxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.default_tax_rate
     *
     * @param defaultTaxRate the value for sim_settings.default_tax_rate
     *
     * @mbg.generated
     */
    public void setDefaultTaxRate(Integer defaultTaxRate) {
        this.defaultTaxRate = defaultTaxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.rows_per_page
     *
     * @return the value of sim_settings.rows_per_page
     *
     * @mbg.generated
     */
    public Integer getRowsPerPage() {
        return rowsPerPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.rows_per_page
     *
     * @param rowsPerPage the value for sim_settings.rows_per_page
     *
     * @mbg.generated
     */
    public void setRowsPerPage(Integer rowsPerPage) {
        this.rowsPerPage = rowsPerPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.no_of_rows
     *
     * @return the value of sim_settings.no_of_rows
     *
     * @mbg.generated
     */
    public Integer getNoOfRows() {
        return noOfRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.no_of_rows
     *
     * @param noOfRows the value for sim_settings.no_of_rows
     *
     * @mbg.generated
     */
    public void setNoOfRows(Integer noOfRows) {
        this.noOfRows = noOfRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.total_rows
     *
     * @return the value of sim_settings.total_rows
     *
     * @mbg.generated
     */
    public Integer getTotalRows() {
        return totalRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.total_rows
     *
     * @param totalRows the value for sim_settings.total_rows
     *
     * @mbg.generated
     */
    public void setTotalRows(Integer totalRows) {
        this.totalRows = totalRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.dateformat
     *
     * @return the value of sim_settings.dateformat
     *
     * @mbg.generated
     */
    public Byte getDateformat() {
        return dateformat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.dateformat
     *
     * @param dateformat the value for sim_settings.dateformat
     *
     * @mbg.generated
     */
    public void setDateformat(Byte dateformat) {
        this.dateformat = dateformat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.print_payment
     *
     * @return the value of sim_settings.print_payment
     *
     * @mbg.generated
     */
    public Byte getPrintPayment() {
        return printPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.print_payment
     *
     * @param printPayment the value for sim_settings.print_payment
     *
     * @mbg.generated
     */
    public void setPrintPayment(Byte printPayment) {
        this.printPayment = printPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.calendar
     *
     * @return the value of sim_settings.calendar
     *
     * @mbg.generated
     */
    public Byte getCalendar() {
        return calendar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.calendar
     *
     * @param calendar the value for sim_settings.calendar
     *
     * @mbg.generated
     */
    public void setCalendar(Byte calendar) {
        this.calendar = calendar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.restrict_sales
     *
     * @return the value of sim_settings.restrict_sales
     *
     * @mbg.generated
     */
    public Byte getRestrictSales() {
        return restrictSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.restrict_sales
     *
     * @param restrictSales the value for sim_settings.restrict_sales
     *
     * @mbg.generated
     */
    public void setRestrictSales(Byte restrictSales) {
        this.restrictSales = restrictSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.major
     *
     * @return the value of sim_settings.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.major
     *
     * @param major the value for sim_settings.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.minor
     *
     * @return the value of sim_settings.minor
     *
     * @mbg.generated
     */
    public String getMinor() {
        return minor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.minor
     *
     * @param minor the value for sim_settings.minor
     *
     * @mbg.generated
     */
    public void setMinor(String minor) {
        this.minor = minor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.display_words
     *
     * @return the value of sim_settings.display_words
     *
     * @mbg.generated
     */
    public Byte getDisplayWords() {
        return displayWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.display_words
     *
     * @param displayWords the value for sim_settings.display_words
     *
     * @mbg.generated
     */
    public void setDisplayWords(Byte displayWords) {
        this.displayWords = displayWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.customer_user
     *
     * @return the value of sim_settings.customer_user
     *
     * @mbg.generated
     */
    public Boolean getCustomerUser() {
        return customerUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.customer_user
     *
     * @param customerUser the value for sim_settings.customer_user
     *
     * @mbg.generated
     */
    public void setCustomerUser(Boolean customerUser) {
        this.customerUser = customerUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.version
     *
     * @return the value of sim_settings.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.version
     *
     * @param version the value for sim_settings.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.email_html
     *
     * @return the value of sim_settings.email_html
     *
     * @mbg.generated
     */
    public Boolean getEmailHtml() {
        return emailHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.email_html
     *
     * @param emailHtml the value for sim_settings.email_html
     *
     * @mbg.generated
     */
    public void setEmailHtml(Boolean emailHtml) {
        this.emailHtml = emailHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.protocol
     *
     * @return the value of sim_settings.protocol
     *
     * @mbg.generated
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.protocol
     *
     * @param protocol the value for sim_settings.protocol
     *
     * @mbg.generated
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.mailpath
     *
     * @return the value of sim_settings.mailpath
     *
     * @mbg.generated
     */
    public String getMailpath() {
        return mailpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.mailpath
     *
     * @param mailpath the value for sim_settings.mailpath
     *
     * @mbg.generated
     */
    public void setMailpath(String mailpath) {
        this.mailpath = mailpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.smtp_host
     *
     * @return the value of sim_settings.smtp_host
     *
     * @mbg.generated
     */
    public String getSmtpHost() {
        return smtpHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.smtp_host
     *
     * @param smtpHost the value for sim_settings.smtp_host
     *
     * @mbg.generated
     */
    public void setSmtpHost(String smtpHost) {
        this.smtpHost = smtpHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.smtp_user
     *
     * @return the value of sim_settings.smtp_user
     *
     * @mbg.generated
     */
    public String getSmtpUser() {
        return smtpUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.smtp_user
     *
     * @param smtpUser the value for sim_settings.smtp_user
     *
     * @mbg.generated
     */
    public void setSmtpUser(String smtpUser) {
        this.smtpUser = smtpUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.smtp_pass
     *
     * @return the value of sim_settings.smtp_pass
     *
     * @mbg.generated
     */
    public String getSmtpPass() {
        return smtpPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.smtp_pass
     *
     * @param smtpPass the value for sim_settings.smtp_pass
     *
     * @mbg.generated
     */
    public void setSmtpPass(String smtpPass) {
        this.smtpPass = smtpPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.smtp_port
     *
     * @return the value of sim_settings.smtp_port
     *
     * @mbg.generated
     */
    public String getSmtpPort() {
        return smtpPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.smtp_port
     *
     * @param smtpPort the value for sim_settings.smtp_port
     *
     * @mbg.generated
     */
    public void setSmtpPort(String smtpPort) {
        this.smtpPort = smtpPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.smtp_crypto
     *
     * @return the value of sim_settings.smtp_crypto
     *
     * @mbg.generated
     */
    public String getSmtpCrypto() {
        return smtpCrypto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.smtp_crypto
     *
     * @param smtpCrypto the value for sim_settings.smtp_crypto
     *
     * @mbg.generated
     */
    public void setSmtpCrypto(String smtpCrypto) {
        this.smtpCrypto = smtpCrypto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.thousands_sep
     *
     * @return the value of sim_settings.thousands_sep
     *
     * @mbg.generated
     */
    public String getThousandsSep() {
        return thousandsSep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.thousands_sep
     *
     * @param thousandsSep the value for sim_settings.thousands_sep
     *
     * @mbg.generated
     */
    public void setThousandsSep(String thousandsSep) {
        this.thousandsSep = thousandsSep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.decimals_sep
     *
     * @return the value of sim_settings.decimals_sep
     *
     * @mbg.generated
     */
    public String getDecimalsSep() {
        return decimalsSep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.decimals_sep
     *
     * @param decimalsSep the value for sim_settings.decimals_sep
     *
     * @mbg.generated
     */
    public void setDecimalsSep(String decimalsSep) {
        this.decimalsSep = decimalsSep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.decimals
     *
     * @return the value of sim_settings.decimals
     *
     * @mbg.generated
     */
    public Byte getDecimals() {
        return decimals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.decimals
     *
     * @param decimals the value for sim_settings.decimals
     *
     * @mbg.generated
     */
    public void setDecimals(Byte decimals) {
        this.decimals = decimals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.default_email
     *
     * @return the value of sim_settings.default_email
     *
     * @mbg.generated
     */
    public String getDefaultEmail() {
        return defaultEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.default_email
     *
     * @param defaultEmail the value for sim_settings.default_email
     *
     * @mbg.generated
     */
    public void setDefaultEmail(String defaultEmail) {
        this.defaultEmail = defaultEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.purchase_code
     *
     * @return the value of sim_settings.purchase_code
     *
     * @mbg.generated
     */
    public String getPurchaseCode() {
        return purchaseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.purchase_code
     *
     * @param purchaseCode the value for sim_settings.purchase_code
     *
     * @mbg.generated
     */
    public void setPurchaseCode(String purchaseCode) {
        this.purchaseCode = purchaseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.envato_username
     *
     * @return the value of sim_settings.envato_username
     *
     * @mbg.generated
     */
    public String getEnvatoUsername() {
        return envatoUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.envato_username
     *
     * @param envatoUsername the value for sim_settings.envato_username
     *
     * @mbg.generated
     */
    public void setEnvatoUsername(String envatoUsername) {
        this.envatoUsername = envatoUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.theme
     *
     * @return the value of sim_settings.theme
     *
     * @mbg.generated
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.theme
     *
     * @param theme the value for sim_settings.theme
     *
     * @mbg.generated
     */
    public void setTheme(String theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_settings.product_discount
     *
     * @return the value of sim_settings.product_discount
     *
     * @mbg.generated
     */
    public Boolean getProductDiscount() {
        return productDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_settings.product_discount
     *
     * @param productDiscount the value for sim_settings.product_discount
     *
     * @mbg.generated
     */
    public void setProductDiscount(Boolean productDiscount) {
        this.productDiscount = productDiscount;
    }
}