package com.lim.cms.entity;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sim_tax_rates
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SimTaxRates extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_tax_rates.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_tax_rates.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_tax_rates.rate
     *
     * @mbg.generated
     */
    private BigDecimal rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_tax_rates.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_tax_rates.id
     *
     * @return the value of sim_tax_rates.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_tax_rates.id
     *
     * @param id the value for sim_tax_rates.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_tax_rates.name
     *
     * @return the value of sim_tax_rates.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_tax_rates.name
     *
     * @param name the value for sim_tax_rates.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_tax_rates.rate
     *
     * @return the value of sim_tax_rates.rate
     *
     * @mbg.generated
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_tax_rates.rate
     *
     * @param rate the value for sim_tax_rates.rate
     *
     * @mbg.generated
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_tax_rates.type
     *
     * @return the value of sim_tax_rates.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_tax_rates.type
     *
     * @param type the value for sim_tax_rates.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }
}