package com.lim.cms.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sim_users_groups
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SimUsersGroups extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_users_groups.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_users_groups.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_users_groups.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_users_groups.id
     *
     * @return the value of sim_users_groups.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_users_groups.id
     *
     * @param id the value for sim_users_groups.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_users_groups.user_id
     *
     * @return the value of sim_users_groups.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_users_groups.user_id
     *
     * @param userId the value for sim_users_groups.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_users_groups.group_id
     *
     * @return the value of sim_users_groups.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_users_groups.group_id
     *
     * @param groupId the value for sim_users_groups.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}