package com.gion.cms.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user_transaction
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TUserTransaction extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction.user_id
     *
     * @mbg.generated
     */
//    private Integer userId;
    private TUser user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction.payment
     *
     * @mbg.generated
     */
    private BigDecimal payment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;
    
    private Integer type;
    
    private Integer deleteFlag;
    
    private BigDecimal point;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction.id
     *
     * @return the value of t_user_transaction.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction.id
     *
     * @param id the value for t_user_transaction.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction.payment
     *
     * @return the value of t_user_transaction.payment
     *
     * @mbg.generated
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction.payment
     *
     * @param payment the value for t_user_transaction.payment
     *
     * @mbg.generated
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction.comment
     *
     * @return the value of t_user_transaction.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction.comment
     *
     * @param comment the value for t_user_transaction.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction.create_time
     *
     * @return the value of t_user_transaction.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction.create_time
     *
     * @param createTime the value for t_user_transaction.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction.update_time
     *
     * @return the value of t_user_transaction.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction.update_time
     *
     * @param updateTime the value for t_user_transaction.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public TUser getUser() {
		return user;
	}

	public void setUser(TUser user) {
		this.user = user;
	}

	public Integer getDeleteFlag() {
		return deleteFlag;
	}

	public void setDeleteFlag(Integer deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public BigDecimal getPoint() {
		return point;
	}

	public void setPoint(BigDecimal point) {
		this.point = point;
	}
}