package com.gion.cms.mapper;

import com.gion.cms.entity.TUserTransaction;
import java.util.List;

public interface TUserTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction
     *
     * @mbg.generated
     */
    int insert(TUserTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction
     *
     * @mbg.generated
     */
    TUserTransaction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction
     *
     * @mbg.generated
     */
    List<TUserTransaction> selectAll();
    
    List<TUserTransaction> selectAllByUserId(Integer id);
    
    List<TUserTransaction> selectAllByPhone(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TUserTransaction record);
    
    int softDelete(TUserTransaction record);
}