package com.gion.cms.mapper;

import com.gion.cms.entity.TUser;
import java.util.List;

public interface TUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int insert(TUser record);
    
    int insertByPhone(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    TUser selectByPrimaryKey(Integer id);
    
    void softDelete(TUser user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    List<TUser> selectAll();
    
    List<TUser> selectAllWIthPoint();
    
    TUser selectUserWIthPointById(int id);
    
    TUser selectUserWIthPointByPhone(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TUser record);
    
    int updatePassword(TUser user);
    
    int addPoints(TUser user);
    
    TUser selectByPhone(String phone);
    
    TUser userLogin(TUser user);
}