package com.lim.cms.mapper;

import com.lim.cms.entity.SimCalendar;
import java.util.List;

public interface SimCalendarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_calendar
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_calendar
     *
     * @mbg.generated
     */
    int insert(SimCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_calendar
     *
     * @mbg.generated
     */
    SimCalendar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_calendar
     *
     * @mbg.generated
     */
    List<SimCalendar> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_calendar
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimCalendar record);
}