package com.lim.cms.mapper;

import com.lim.cms.entity.SimCustomers;
import java.util.List;

public interface SimCustomersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_customers
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_customers
     *
     * @mbg.generated
     */
    int insert(SimCustomers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_customers
     *
     * @mbg.generated
     */
    SimCustomers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_customers
     *
     * @mbg.generated
     */
    List<SimCustomers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_customers
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimCustomers record);
}