package com.lim.cms.mapper;

import com.lim.cms.entity.SimCompany;
import java.util.List;

public interface SimCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_company
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_company
     *
     * @mbg.generated
     */
    int insert(SimCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_company
     *
     * @mbg.generated
     */
    SimCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_company
     *
     * @mbg.generated
     */
    List<SimCompany> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimCompany record);
}