package com.lim.cms.mapper;

import com.lim.cms.entity.SimDateFormat;
import java.util.List;

public interface SimDateFormatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_date_format
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_date_format
     *
     * @mbg.generated
     */
    int insert(SimDateFormat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_date_format
     *
     * @mbg.generated
     */
    SimDateFormat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_date_format
     *
     * @mbg.generated
     */
    List<SimDateFormat> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_date_format
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimDateFormat record);
}