package com.lim.cms.mapper;

import com.lim.cms.entity.SimGroups;
import java.util.List;

public interface SimGroupsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_groups
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_groups
     *
     * @mbg.generated
     */
    int insert(SimGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_groups
     *
     * @mbg.generated
     */
    SimGroups selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_groups
     *
     * @mbg.generated
     */
    List<SimGroups> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_groups
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimGroups record);
}