package com.lim.cms.mapper;

import com.lim.cms.entity.SimLoginAttempts;
import java.util.List;

public interface SimLoginAttemptsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_login_attempts
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_login_attempts
     *
     * @mbg.generated
     */
    int insert(SimLoginAttempts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_login_attempts
     *
     * @mbg.generated
     */
    SimLoginAttempts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_login_attempts
     *
     * @mbg.generated
     */
    List<SimLoginAttempts> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_login_attempts
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimLoginAttempts record);
}