package com.lim.cms.mapper;

import com.lim.cms.entity.SimMigrations;
import java.util.List;

public interface SimMigrationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_migrations
     *
     * @mbg.generated
     */
    int insert(SimMigrations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_migrations
     *
     * @mbg.generated
     */
    List<SimMigrations> selectAll();
}