package com.lim.cms.mapper;

import com.lim.cms.entity.SimNotes;
import java.util.List;

public interface SimNotesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_notes
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_notes
     *
     * @mbg.generated
     */
    int insert(SimNotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_notes
     *
     * @mbg.generated
     */
    SimNotes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_notes
     *
     * @mbg.generated
     */
    List<SimNotes> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_notes
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimNotes record);
}