package com.lim.cms.mapper;

import java.util.List;

import com.lim.cms.entity.SimPayment;
import com.lim.cms.entity.SimPaymentReportCriteria;
import com.lim.cms.entity.SimSales;

public interface SimPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_payment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_payment
     *
     * @mbg.generated
     */
    int insert(SimPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_payment
     *
     * @mbg.generated
     */
    SimPayment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_payment
     *
     * @mbg.generated
     */
    List<SimPayment> selectAll();
    
    List<SimPayment> selectAllBySaleId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimPayment record);
    
    List<SimPayment> selectAllByCondition(SimPaymentReportCriteria criteria);
}