package com.lim.cms.mapper;

import com.lim.cms.entity.SimQuotes;
import java.util.List;

public interface SimQuotesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_quotes
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_quotes
     *
     * @mbg.generated
     */
    int insert(SimQuotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_quotes
     *
     * @mbg.generated
     */
    SimQuotes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_quotes
     *
     * @mbg.generated
     */
    List<SimQuotes> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_quotes
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimQuotes record);
}