package com.lim.cms.mapper;

import com.lim.cms.entity.SimQuoteItems;
import java.util.List;

public interface SimQuoteItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_quote_items
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_quote_items
     *
     * @mbg.generated
     */
    int insert(SimQuoteItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_quote_items
     *
     * @mbg.generated
     */
    SimQuoteItems selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_quote_items
     *
     * @mbg.generated
     */
    List<SimQuoteItems> selectAll();
    
    List<SimQuoteItems> selectAllByQuoteId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_quote_items
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimQuoteItems record);
}