package com.lim.cms.mapper;

import com.lim.cms.entity.SimSessions;
import java.util.List;

public interface SimSessionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_sessions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_sessions
     *
     * @mbg.generated
     */
    int insert(SimSessions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_sessions
     *
     * @mbg.generated
     */
    SimSessions selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_sessions
     *
     * @mbg.generated
     */
    List<SimSessions> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_sessions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimSessions record);
}