package com.lim.cms.mapper;

import com.lim.cms.entity.SimStripe;
import java.util.List;

public interface SimStripeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_stripe
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_stripe
     *
     * @mbg.generated
     */
    int insert(SimStripe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_stripe
     *
     * @mbg.generated
     */
    SimStripe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_stripe
     *
     * @mbg.generated
     */
    List<SimStripe> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_stripe
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimStripe record);
}