package com.lim.cms.mapper;

import java.util.List;

import com.lim.cms.entity.SimSales;
import com.lim.cms.entity.SimSalesReportCriteria;

public interface SimSalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_sales
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_sales
     *
     * @mbg.generated
     */
    int insert(SimSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_sales
     *
     * @mbg.generated
     */
    SimSales selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_sales
     *
     * @mbg.generated
     */
    List<SimSales> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_sales
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimSales record);
    
    
    List<SimSales> selectAllByCondition(SimSalesReportCriteria criteria);
}