package com.lim.cms.mapper;

import com.lim.cms.entity.SimQuoteItems;
import com.lim.cms.entity.SimSaleItems;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SimSaleItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_sale_items
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_sale_items
     *
     * @mbg.generated
     */
    int insert(SimSaleItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_sale_items
     *
     * @mbg.generated
     */
    SimSaleItems selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_sale_items
     *
     * @mbg.generated
     */
    List<SimSaleItems> selectAll();
    
    List<SimSaleItems> selectAllBySaleId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_sale_items
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimSaleItems record);
    
    int bulkInsert(@Param(value = "record") List<SimSaleItems> record);
    
    int bulkUpdate(@Param(value = "record") List<SimSaleItems> record);
    
    int bulkDelete(@Param(value = "record") List<SimSaleItems> record);
}