package com.lim.cms.mapper;

import com.lim.cms.entity.SimTaxRates;
import java.util.List;

public interface SimTaxRatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_tax_rates
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_tax_rates
     *
     * @mbg.generated
     */
    int insert(SimTaxRates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_tax_rates
     *
     * @mbg.generated
     */
    SimTaxRates selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_tax_rates
     *
     * @mbg.generated
     */
    List<SimTaxRates> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_tax_rates
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimTaxRates record);
}