package com.lim.cms.mapper;

import com.lim.cms.entity.SimUsers;
import java.util.List;

public interface SimUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_users
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_users
     *
     * @mbg.generated
     */
    int insert(SimUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_users
     *
     * @mbg.generated
     */
    SimUsers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_users
     *
     * @mbg.generated
     */
    List<SimUsers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimUsers record);
}