package com.lim.cms.mapper;

import com.lim.cms.entity.SimUsersGroups;
import java.util.List;

public interface SimUsersGroupsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_users_groups
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_users_groups
     *
     * @mbg.generated
     */
    int insert(SimUsersGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_users_groups
     *
     * @mbg.generated
     */
    SimUsersGroups selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_users_groups
     *
     * @mbg.generated
     */
    List<SimUsersGroups> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_users_groups
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimUsersGroups record);
}