package com.lim.cms.mapper;

import com.lim.cms.entity.SimUsers;
import java.util.List;

public interface SimUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_users
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_users
     *
     * @mbg.generated
     */
    int insert(SimUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_users
     *
     * @mbg.generated
     */
    SimUsers selectByPrimaryKey(Integer id);
    
    
    SimUsers loginAuth(SimUsers user);
    
    SimUsers selectByEmail(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_users
     *
     * @mbg.generated
     */
    List<SimUsers> selectAll();
    
    List<SimUsers> selectAllByCustomerId(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimUsers record);
}